CREATE TABLE IF NOT EXISTS uni_v3_indexer_checkpoint (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    chain_id BIGINT NOT NULL,
    pool_address VARCHAR(64) NOT NULL,
    pool_name VARCHAR(128) NOT NULL,
    start_block BIGINT NOT NULL,
    last_scanned_block BIGINT NOT NULL,
    last_committed_block BIGINT NOT NULL,
    last_committed_block_hash VARCHAR(80) NULL,
    confirmations INT NOT NULL DEFAULT 6,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_chain_pool (chain_id, pool_address)
);

CREATE TABLE IF NOT EXISTS uni_v3_pool_event (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    event_uid VARCHAR(160) NOT NULL,
    chain_id BIGINT NOT NULL,
    pool_address VARCHAR(64) NOT NULL,
    pool_name VARCHAR(128) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    block_number BIGINT NOT NULL,
    block_hash VARCHAR(80) NOT NULL,
    transaction_hash VARCHAR(80) NOT NULL,
    transaction_index INT NOT NULL,
    log_index INT NOT NULL,
    block_time BIGINT NOT NULL,
    sender VARCHAR(64) NULL,
    recipient VARCHAR(64) NULL,
    owner_address VARCHAR(64) NULL,
    tick_lower INT NULL,
    tick_upper INT NULL,
    amount VARCHAR(120) NULL,
    amount0 VARCHAR(120) NULL,
    amount1 VARCHAR(120) NULL,
    sqrt_price_x96 VARCHAR(120) NULL,
    liquidity VARCHAR(120) NULL,
    tick INT NULL,
    paid0 VARCHAR(120) NULL,
    paid1 VARCHAR(120) NULL,
    summary VARCHAR(512) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_event_uid (event_uid),
    UNIQUE KEY uk_chain_pool_order (chain_id, pool_address, block_number, transaction_index, log_index),
    KEY idx_pool_block (chain_id, pool_address, block_number DESC),
    KEY idx_pool_type_block (chain_id, pool_address, event_type, block_number DESC)
);
